# Generated by Django 4.0.6 on 2022-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Correo del usuario')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del usuario')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del usuario')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado del usuario')),
                ('administrador', models.BooleanField(default=False, verbose_name='¿El usuario es administrador?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
