# Generated by Django 4.0.6 on 2022-07-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False, verbose_name='Identificador de sensor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del sensor')),
                ('fecha_cracion', models.DateField(auto_now_add=True, verbose_name='Fecha en que se creo el sensor')),
                ('modulo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='modulo.modulomodel')),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensores',
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='ValorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de valor')),
                ('medida', models.PositiveIntegerField(verbose_name='Valor de la medida del sensor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la medicion')),
                ('fecha_medicion', models.DateField(auto_now_add=True, verbose_name='Fecha en que se tomo la medida')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='sensor.sensormodel')),
            ],
            options={
                'verbose_name': 'valor',
                'verbose_name_plural': 'valores',
                'db_table': 'valor',
            },
        ),
    ]
