# Generated by Django 4.0.6 on 2022-07-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormodel',
            name='modulo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='modulo.modulomodel'),
        ),
    ]
