# Generated by Django 4.0.6 on 2022-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del elemento')),
                ('fecha_modificacion', models.DateField(auto_now_add=True, verbose_name='Fecha en la que se edito el elemento')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha en que se creo el elemento')),
                ('sensor_id', models.CharField(max_length=12, verbose_name='Identificador del modulo')),
            ],
            options={
                'verbose_name': 'modulo',
                'verbose_name_plural': 'modulos',
                'db_table': 'modulo',
            },
        ),
    ]
