# Generated by Django 4.0.6 on 2022-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloModel',
            fields=[
                ('id', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False, verbose_name='Identificador de modulo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del modulo')),
                ('fecha_cracion', models.DateField(auto_now_add=True, verbose_name='Fecha en que se creo el modulo')),
            ],
            options={
                'verbose_name': 'modulo',
                'verbose_name_plural': 'modulos',
                'db_table': 'modulo',
            },
        ),
    ]
